tailscale_tags: ['clients']
tailscale_args: "--reset --force-reauth --login-server https://vpn.example.com --accept-routes --advertise-routes=192.168.1.1/32,{{{ ip_address | ansible.utils.ipaddr('network/prefix') }}"
tailscale_authkey: "{{ lookup('env', 'TAILSCALE_KEY_CLIENTS') }}"
