---
- name: Ensure sysctl configuration file exists
  ansible.builtin.file:
    path: /etc/sysctl.d/99-tailscale.conf
    state: touch
    owner: root
    group: root
    mode: '0644'

- name: Ensure IPv4 forwarding is enabled
  ansible.builtin.lineinfile:
    path: /etc/sysctl.d/99-tailscale.conf
    line: 'net.ipv4.ip_forward = 1'
    state: present
    
- name: Ensure IPv6 forwarding is enabled
  ansible.builtin.lineinfile:
    path: /etc/sysctl.d/99-tailscale.conf
    line: 'net.ipv6.conf.all.forwarding = 1'
    state: present
    
- name: Apply sysctl settings
  ansible.builtin.command: sysctl -p /etc/sysctl.d/99-tailscale.conf
